accum_grad: 16
cmvn: global_cmvn
cmvn_conf:
  cmvn_file: ../pretrained/global_cmvn
  is_json_cmvn: true
ctc: ctc
ctc_conf:
  ctc_blank_id: 0
dataset: asr
dataset_conf:
  batch_conf:
    batch_size: 32
    batch_type: dynamic
    max_frames_in_batch: 24000
  fbank_conf:
    dither: 1.0
    frame_length: 25
    frame_shift: 10
    num_mel_bins: 80
  filter_conf:
    max_length: 1200
    min_length: 10
    token_max_length: 100
    token_min_length: 1
  resample_conf:
    resample_rate: 16000
  shuffle: true
  shuffle_conf:
    shuffle_size: 20000
  sort: true
  sort_conf:
    sort_size: 2000
  spec_aug: true
  spec_aug_conf:
    max_f: 30
    max_t: 50
    num_f_mask: 2
    num_t_mask: 2
  speed_perturb: true
decoder: bitransformer
decoder_conf:
  attention_heads: 8
  dropout_rate: 0.1
  linear_units: 2048
  num_blocks: 3
  positional_dropout_rate: 0.1
  r_num_blocks: 3
  self_attention_dropout_rate: 0.1
  src_attention_dropout_rate: 0.1
dtype: fp32
encoder: conformer
encoder_conf:
  activation_type: swish
  attention_dropout_rate: 0.1
  attention_heads: 8
  causal: true
  cnn_module_kernel: 15
  cnn_module_norm: layer_norm
  dropout_rate: 0.1
  input_layer: conv2d
  linear_units: 2048
  normalize_before: true
  num_blocks: 12
  output_size: 512
  pos_enc_layer_type: rel_pos
  positional_dropout_rate: 0.1
  selfattention_layer_type: rel_selfattn
  use_cnn_module: true
  use_dynamic_chunk: true
  use_dynamic_left_chunk: false
epoch: 129
grad_clip: 5
input_dim: 80
log_interval: 10
loss_dict:
  acc: 0.8920613527297974
  loss: 14.225177145004272
  loss_att: 13.410273383458456
  loss_ctc: 16.126618633270265
lr: 4.9e-06
max_epoch: 130
model: asr_model
model_conf:
  ctc_weight: 0.3
  length_normalized_loss: false
  lsm_weight: 0.1
  reverse_weight: 0.3
model_dir: exp/conformer
optim: adam
optim_conf:
  lr: 0.002
output_dim: 5538
save_states: model_only
save_time: 25/02/2024 17:19:50
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 100000
step: 244
tokenizer: radio
tokenizer_conf:
  bpe_path: null
  is_multilingual: false
  non_lang_syms_path: null
  num_languages: 1
  special_tokens:
    <blank>: 0
    <eos>: 2
    <sos>: 2
    <unk>: 1
  split_with_space: false
  symbol_table_path: ../pretrained/units.txt
train_engine: torch_ddp
use_amp: false
vocab_size: 5538
